export enum StrollCategory {
	ARCHITECTURE = 'ARCHITECTURE',
	ART = 'ART',
	CONTEMPORARY = 'CONTEMPORARY',
	HISTORICAL = 'HISTORICAL',
	GASTRO = 'GASTRO',
	BUILDING = 'BUILDING',
	SIGHTSEEING = 'SIGHTSEEING',
	SCIENCE = 'SCIENCE',
	LANDSCAPE = 'LANDSCAPE',
	URBANISM = 'URBANISM',
	RELIGION = 'RELIGION',
	SHOPPING = 'SHOPPING',
	ENTERTAINMENT = 'ENTERTAINMENT',
	SPORTS = 'SPORTS'
}
